name: Generate 8-bit Artwork

on:
  push:
    branches:
      - main

jobs:
  generate_artwork:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install Pillow  # Install the required library

      - name: Get Commit SHA
        id: extract_sha
        run: echo "commit_sha=$(git log --format=%H -1)" >> $GITHUB_OUTPUT

      - name: Generate 8-bit Artwork
        run: |
          python generate_artwork.py ${{ steps.extract_sha.outputs.commit_sha }}
          mkdir -p artwork
          mv *.png artwork/

      - name: Archive Artwork as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: generated-artwork
          path: artwork
